# Generated by Django 6.0 on 2025-12-23 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authapp", "0002_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="cart_temporary",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
