services:
  nginx:
    image: nginx:latest
    container_name: nginx-server
    expose:
      - 8088
    ports:
      - "80:8088"
    restart: always
    volumes:
      - ./project/static:/app/www/cozyshop/static
      - ./project/media:/app/www/cozyshop/media
      - ./project/logs:/app/www/cozyshop/logs
      - ./nginx:/etc/nginx/conf.d
    networks:
      - dbnet
    depends_on:
      - cozyshop

  postgres:
    image: postgres:17-alpine
    container_name: psgr
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    env_file:
      - .env
    networks:
      - dbnet

  cozyshop:
    build: ./project
    image: cozyshop
    container_name: cozyshop
    ports:
      - "8000:8000"
    restart: always
    command: [
      "uvicorn", "config.asgi:application",
      "--host", "0.0.0.0",
      "--port", "8000",
      "--log-level", "debug",
      "--reload-include", "*.html",
      "--reload" ] # "--workers", "4",
    volumes:
      - ./project:/app/www/cozyshop
    environment:
      # DB settings
      DB_ENGINE: ${DB_ENGINE}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}

      # Secret Key
      SECRET_KEY: ${SECRET_KEY}
      # Debug mode
      DEBUG: ${DEBUG}
      # Allowed hosts
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
      CSRF_TRUSTED_ORIGINS: ${CSRF_TRUSTED_ORIGINS}

      # Email settings
      EMAIL_BACKEND: ${EMAIL_BACKEND}
      EMAIL_USE_TLS: ${EMAIL_USE_TLS}
      EMAIL_USE_SSL: ${EMAIL_USE_SSL}
      DEFAULT_FROM_EMAIL: ${DEFAULT_FROM_EMAIL}
      EMAIL_HOST: ${EMAIL_HOST}
      EMAIL_HOST_USER: ${EMAIL_HOST_USER}
      EMAIL_HOST_PASSWORD: ${EMAIL_HOST_PASSWORD}
      EMAIL_PORT: ${EMAIL_PORT}

      # PayPal
      PAYPAL_TEST: ${PAYPAL_TEST}
      PAYPAL_RECEIVER_EMAIL: ${PAYPAL_RECEIVER_EMAIL}
    env_file:
      - .env
    links:
      - "postgres:dbps"
    networks:
      - dbnet
    depends_on:
      - postgres

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8080:8080"
    links:
      - "postgres:db"
    networks:
      - dbnet
    depends_on:
      - postgres

networks:
  dbnet:
    driver: bridge

volumes:
  postgres_data: