# Generated by Django 5.2.8 on 2025-11-20 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="sale",
            field=models.FloatField(
                default=0, help_text="The value must be between 0 and 1"
            ),
        ),
    ]
