CATEGORIES = [
    {
        "id": 1,
        "name": "Cozy Blankets",
        "slug": "cozy-blankets",
        "image": "https://images.unsplash.com/photo-1504196606672-aef5c9cefc92",
        "description": "Enjoy the winter season with a stylish cup of tea. Perfect for cozy mornings and relaxing evenings. Like and follow us for more!",
    },
    {
        "id": 2,
        "name": "Warm Lighting",
        "slug": "warm-lighting",
        "image": "https://images.unsplash.com/photo-1504196606672-aef5c9cefc92",
        "description": "Enjoy the winter season with a stylish cup of tea. Perfect for cozy mornings and relaxing evenings. Like and follow us for more!",
    },
    {
        "id": 3,
        "name": "Scented Candles",
        "slug": "scented-candles",
        "image": "https://images.unsplash.com/photo-1504196606672-aef5c9cefc92",
        "description": "Enjoy the winter season with a stylish cup of tea. Perfect for cozy mornings and relaxing evenings. Like and follow us for more!",
    },
    {
        "id": 4,
        "name": "Comfortable Pillows",
        "slug": "comfortable-pillows",
        "image": "https://images.unsplash.com/photo-1504196606672-aef5c9cefc92",
        "description": "Enjoy the winter season with a stylish cup of tea. Perfect for cozy mornings and relaxing evenings. Like and follow us for more!",
    },
    {
        "id": 5,
        "name": "Soft Rugs",
        "slug": "soft-rugs",
        "image": "https://images.unsplash.com/photo-1504196606672-aef5c9cefc92",
        "description": "Enjoy the winter season with a stylish cup of tea. Perfect for cozy mornings and relaxing evenings. Like and follow us for more!",
    },
    {
        "id": 6,
        "name": "Home Slippers",
        "slug": "home-slippers",
        "image": "https://images.unsplash.com/photo-1504196606672-aef5c9cefc92",
        "description": "Enjoy the winter season with a stylish cup of tea. Perfect for cozy mornings and relaxing evenings. Like and follow us for more!",
    },
    {
        "id": 7,
        "name": "Tea & Mugs",
        "slug": "tea-and-mugs",
        "image": "https://images.unsplash.com/photo-1504196606672-aef5c9cefc92",
        "description": "Enjoy the winter season with a stylish cup of tea. Perfect for cozy mornings and relaxing evenings. Like and follow us for more!",
    },
    {
        "id": 8,
        "name": "Aromatherapy",
        "slug": "aromatherapy",
        "image": "https://images.unsplash.com/photo-1504196606672-aef5c9cefc92",
        "description": "Enjoy the winter season with a stylish cup of tea. Perfect for cozy mornings and relaxing evenings. Like and follow us for more!",
    },
    {
        "id": 9,
        "name": "Decor Accessories",
        "slug": "decor-accessories",
        "image": "https://images.unsplash.com/photo-1504196606672-aef5c9cefc92",
        "description": "Enjoy the winter season with a stylish cup of tea. Perfect for cozy mornings and relaxing evenings. Like and follow us for more!",
    },
]

PRODUCTS = [
    # Category 1 – Cozy Blankets (6)
    {
        "id": 1,
        "category_id": 1,
        "slug": "fluffy-winter-blanket",
        "name": "Fluffy Winter Blanket",
        "image": "https://images.unsplash.com/photo-1528756514091-dee5ecaa3278",
        "price": 49.99,
        "sale": 0.10,
        "in_stock": True,
    },
    {
        "id": 2,
        "category_id": 1,
        "slug": "knitted-soft-blanket",
        "name": "Knitted Soft Blanket",
        "image": "https://images.unsplash.com/photo-1504196606672-aef5c9cefc92",
        "price": 59.99,
        "sale": 0.15,
        "in_stock": True,
    },
    {
        "id": 3,
        "category_id": 1,
        "slug": "plaid-cozy-throw",
        "name": "Plaid Cozy Throw",
        "image": "https://images.unsplash.com/photo-1519710164239-da123dc03ef4",
        "price": 39.99,
        "sale": 0.00,
        "in_stock": True,
    },
    {
        "id": 4,
        "category_id": 1,
        "slug": "weighted-comfort-blanket",
        "name": "Weighted Comfort Blanket",
        "image": "https://images.unsplash.com/photo-1519710164239-da123dc03ef4",
        "price": 89.99,
        "sale": 0.20,
        "in_stock": True,
    },
    {
        "id": 5,
        "category_id": 1,
        "slug": "microfiber-dream-throw",
        "name": "Microfiber Dream Throw",
        "image": "https://images.unsplash.com/photo-1519710164239-da123dc03ef4",
        "price": 44.99,
        "sale": 0.05,
        "in_stock": False,
    },
    {
        "id": 6,
        "category_id": 1,
        "slug": "luxury-fleece-blanket",
        "name": "Luxury Fleece Blanket",
        "image": "https://images.unsplash.com/photo-1528756514091-dee5ecaa3278",
        "price": 69.99,
        "sale": 0.10,
        "in_stock": True,
    },
    # Category 2 – Warm Lighting (6)
    {
        "id": 7,
        "category_id": 2,
        "slug": "amber-table-lamp",
        "name": "Amber Table Lamp",
        "image": "https://images.unsplash.com/photo-1503602642458-232111445657",
        "price": 34.99,
        "sale": 0.00,
        "in_stock": True,
    },
    {
        "id": 8,
        "category_id": 2,
        "slug": "warm-led-string-lights",
        "name": "Warm LED String Lights",
        "image": "https://images.unsplash.com/photo-1519710164239-da123dc03ef4",
        "price": 19.99,
        "sale": 0.10,
        "in_stock": True,
    },
    {
        "id": 9,
        "category_id": 2,
        "slug": "golden-glow-lamp",
        "name": "Golden Glow Lamp",
        "image": "https://images.unsplash.com/photo-1481277542470-605612bd2d61",
        "price": 59.99,
        "sale": 0.05,
        "in_stock": True,
    },
    {
        "id": 10,
        "category_id": 2,
        "slug": "touch-night-light",
        "name": "Touch Night Light",
        "image": "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b",
        "price": 24.99,
        "sale": 0.00,
        "in_stock": False,
    },
    {
        "id": 11,
        "category_id": 2,
        "slug": "himalayan-salt-lamp",
        "name": "Himalayan Salt Lamp",
        "name": "Himalayan Salt Lamp",
        "image": "https://images.unsplash.com/photo-1519710164239-da123dc03ef4",
        "price": 29.99,
        "sale": 0.20,
        "in_stock": True,
    },
    {
        "id": 12,
        "category_id": 2,
        "slug": "mini-desk-warm-light",
        "name": "Mini Desk Warm Light",
        "image": "https://images.unsplash.com/photo-1503602642458-232111445657",
        "price": 14.99,
        "sale": 0.00,
        "in_stock": True,
    },
    # Category 3 – Scented Candles (6)
    {
        "id": 13,
        "category_id": 3,
        "slug": "vanilla-bean-candle",
        "name": "Vanilla Bean Candle",
        "image": "https://images.unsplash.com/photo-1503602642458-232111445657",
        "price": 12.99,
        "sale": 0.10,
        "in_stock": True,
    },
    {
        "id": 14,
        "category_id": 3,
        "slug": "lavender-relax-candle",
        "name": "Lavender Relax Candle",
        "image": "https://images.unsplash.com/photo-1503602642458-232111445657",
        "price": 15.99,
        "sale": 0.00,
        "in_stock": True,
    },
    {
        "id": 15,
        "category_id": 3,
        "slug": "rose-blossom-candle",
        "name": "Rose Blossom Candle",
        "image": "https://images.unsplash.com/photo-1517685352821-92cf88aee5a5",
        "price": 13.99,
        "sale": 0.05,
        "in_stock": True,
    },
    {
        "id": 16,
        "category_id": 3,
        "slug": "autumn-spice-candle",
        "name": "Autumn Spice Candle",
        "image": "https://images.unsplash.com/photo-1504196606672-aef5c9cefc92",
        "price": 16.99,
        "sale": 0.10,
        "in_stock": False,
    },
    {
        "id": 17,
        "category_id": 3,
        "slug": "cedarwood-warm-candle",
        "name": "Cedarwood Warm Candle",
        "image": "https://images.unsplash.com/photo-1505691938895-1758d7feb511",
        "price": 14.99,
        "sale": 0.15,
        "in_stock": True,
    },
    {
        "id": 18,
        "category_id": 3,
        "slug": "ocean-breeze-candle",
        "name": "Ocean Breeze Candle",
        "image": "https://images.unsplash.com/photo-1503602642458-232111445657",
        "price": 11.99,
        "sale": 0.00,
        "in_stock": True,
    },
    # Category 4 – Comfortable Pillows (6)
    {
        "id": 19,
        "category_id": 4,
        "slug": "feather-soft-pillow",
        "name": "Feather Soft Pillow",
        "image": "https://images.unsplash.com/photo-1528756514091-dee5ecaa3278",
        "price": 24.99,
        "sale": 0.10,
        "in_stock": True,
    },
    {
        "id": 20,
        "category_id": 4,
        "slug": "ergonomic-sleep-pillow",
        "name": "Ergonomic Sleep Pillow",
        "image": "https://images.unsplash.com/photo-1505691938895-1758d7feb511",
        "price": 34.99,
        "sale": 0.00,
        "in_stock": True,
    },
    {
        "id": 21,
        "category_id": 4,
        "slug": "memory-foam-pillow",
        "name": "Memory Foam Pillow",
        "image": "https://images.unsplash.com/photo-1524758631624-e2822e304c36",
        "price": 39.99,
        "sale": 0.15,
        "in_stock": False,
    },
    {
        "id": 22,
        "category_id": 4,
        "slug": "microfiber-casual-pillow",
        "name": "Microfiber Casual Pillow",
        "image": "https://images.unsplash.com/photo-1524758631624-e2822e304c36",
        "price": 19.99,
        "sale": 0.00,
        "in_stock": True,
    },
    {
        "id": 23,
        "category_id": 4,
        "slug": "lux-cotton-pillow",
        "name": "Lux Cotton Pillow",
        "image": "https://images.unsplash.com/photo-1521401830884-6c03c1c87ebb",
        "price": 29.99,
        "sale": 0.05,
        "in_stock": True,
    },
    {
        "id": 24,
        "category_id": 4,
        "slug": "cozy-knit-pillow",
        "name": "Cozy Knit Pillow",
        "image": "https://images.unsplash.com/photo-1586023492125-27b2c045efd7",
        "price": 22.99,
        "sale": 0.00,
        "in_stock": True,
    },
    # Category 5 – Soft Rugs (6)
    {
        "id": 25,
        "category_id": 5,
        "slug": "fuzzy-round-rug",
        "name": "Fuzzy Round Rug",
        "image": "https://images.unsplash.com/photo-1600585154340-be6161a56a0c",
        "price": 49.99,
        "sale": 0.10,
        "in_stock": True,
    },
    {
        "id": 26,
        "category_id": 5,
        "slug": "shaggy-plush-rug",
        "name": "Shaggy Plush Rug",
        "image": "https://images.unsplash.com/photo-1528756514091-dee5ecaa3278",
        "price": 79.99,
        "sale": 0.05,
        "in_stock": True,
    },
    {
        "id": 27,
        "category_id": 5,
        "slug": "woven-natural-rug",
        "name": "Woven Natural Rug",
        "image": "https://images.unsplash.com/photo-1586023492125-27b2c045efd7",
        "price": 59.99,
        "sale": 0.00,
        "in_stock": False,
    },
    {
        "id": 28,
        "category_id": 5,
        "slug": "cotton-entry-rug",
        "name": "Cotton Entry Rug",
        "image": "https://images.unsplash.com/photo-1555041469-a586c61ea9bc",
        "price": 29.99,
        "sale": 0.00,
        "in_stock": True,
    },
    {
        "id": 29,
        "category_id": 5,
        "slug": "microfiber-floor-rug",
        "name": "Microfiber Floor Rug",
        "image": "https://images.unsplash.com/photo-1528756514091-dee5ecaa3278",
        "price": 39.99,
        "sale": 0.10,
        "in_stock": True,
    },
    {
        "id": 30,
        "category_id": 5,
        "slug": "premium-soft-rug",
        "name": "Premium Soft Rug",
        "image": "https://images.unsplash.com/photo-1505691938895-1758d7feb511",
        "price": 89.99,
        "sale": 0.20,
        "in_stock": True,
    },
    # Category 6 – Home Slippers (6)
    {
        "id": 31,
        "category_id": 6,
        "slug": "plush-home-slippers",
        "name": "Plush Home Slippers",
        "image": "https://images.unsplash.com/photo-1528756514091-dee5ecaa3278",
        "price": 19.99,
        "sale": 0.10,
        "in_stock": True,
    },
    {
        "id": 32,
        "category_id": 6,
        "slug": "cotton-slip-ons",
        "name": "Cotton Slip-Ons",
        "image": "https://images.unsplash.com/photo-1528756514091-dee5ecaa3278",
        "price": 14.99,
        "sale": 0.00,
        "in_stock": True,
    },
    {
        "id": 33,
        "category_id": 6,
        "slug": "warm-fur-slippers",
        "name": "Warm Fur Slippers",
        "image": "https://images.unsplash.com/photo-1528756514091-dee5ecaa3278",
        "price": 24.99,
        "sale": 0.15,
        "in_stock": True,
    },
    {
        "id": 34,
        "category_id": 6,
        "slug": "foam-step-slippers",
        "name": "Foam Step Slippers",
        "image": "https://images.unsplash.com/photo-1505691938895-1758d7feb511",
        "price": 17.99,
        "sale": 0.00,
        "in_stock": False,
    },
    {
        "id": 35,
        "category_id": 6,
        "slug": "cozy-knit-slippers",
        "name": "Cozy Knit Slippers",
        "image": "https://images.unsplash.com/photo-1505691938895-1758d7feb511",
        "price": 21.99,
        "sale": 0.05,
        "in_stock": True,
    },
    {
        "id": 36,
        "category_id": 6,
        "slug": "memory-foam-slippers",
        "name": "Memory Foam Slippers",
        "image": "https://images.unsplash.com/photo-1528756514091-dee5ecaa3278",
        "price": 26.99,
        "sale": 0.10,
        "in_stock": True,
    },
    # Category 7 – Tea & Mugs (6)
    {
        "id": 37,
        "category_id": 7,
        "slug": "ceramic-cozy-mug",
        "name": "Ceramic Cozy Mug",
        "image": "https://images.unsplash.com/photo-1517685352821-92cf88aee5a5",
        "price": 12.99,
        "sale": 0.00,
        "in_stock": True,
    },
    {
        "id": 38,
        "category_id": 7,
        "slug": "leaf-tea-collection",
        "name": "Leaf Tea Collection",
        "image": "https://images.unsplash.com/photo-1470337458703-46ad1756a187",
        "price": 22.99,
        "sale": 0.10,
        "in_stock": True,
    },
    {
        "id": 39,
        "category_id": 7,
        "slug": "honey-ginger-tea",
        "name": "Honey Ginger Tea",
        "image": "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd",
        "price": 14.99,
        "sale": 0.05,
        "in_stock": True,
    },
    {
        "id": 40,
        "category_id": 7,
        "slug": "speckled-morning-mug",
        "name": "Speckled Morning Mug",
        "image": "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd",
        "price": 11.99,
        "sale": 0.00,
        "in_stock": False,
    },
    {
        "id": 41,
        "category_id": 7,
        "slug": "herbal-relax-tea",
        "name": "Herbal Relax Tea",
        "image": "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd",
        "price": 13.99,
        "sale": 0.10,
        "in_stock": True,
    },
    {
        "id": 42,
        "category_id": 7,
        "slug": "wood-handle-mug",
        "name": "Wood Handle Mug",
        "image": "https://images.unsplash.com/photo-1505691938895-1758d7feb511",
        "price": 16.99,
        "sale": 0.00,
        "in_stock": True,
    },
    # Category 8 – Aromatherapy (4)
    {
        "id": 43,
        "category_id": 8,
        "slug": "essential-oil-set",
        "name": "Essential Oil Set",
        "image": "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b",
        "price": 29.99,
        "sale": 0.10,
        "in_stock": True,
    },
    {
        "id": 44,
        "category_id": 8,
        "slug": "aroma-diffuser-lite",
        "name": "Aroma Diffuser Lite",
        "image": "https://images.unsplash.com/photo-1504196606672-aef5c9cefc92",
        "price": 39.99,
        "sale": 0.00,
        "in_stock": True,
    },
    {
        "id": 45,
        "category_id": 8,
        "slug": "lavender-oil-dropper",
        "name": "Lavender Oil Dropper",
        "image": "https://images.unsplash.com/photo-1505691938895-1758d7feb511",
        "price": 12.99,
        "sale": 0.05,
        "in_stock": True,
    },
    {
        "id": 46,
        "category_id": 8,
        "slug": "mint-refresh-oil",
        "name": "Mint Refresh Oil",
        "image": "https://images.unsplash.com/photo-1505691938895-1758d7feb511",
        "price": 10.99,
        "sale": 0.00,
        "in_stock": False,
    },
    # Category 9 – Decor Accessories (4)
    {
        "id": 47,
        "category_id": 9,
        "slug": "wood-table-tray",
        "name": "Wood Table Tray",
        "image": "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b",
        "price": 22.99,
        "sale": 0.00,
        "in_stock": True,
    },
    {
        "id": 48,
        "category_id": 9,
        "slug": "woven-storage-basket",
        "name": "Woven Storage Basket",
        "image": "https://images.unsplash.com/photo-1505691938895-1758d7feb511",
        "price": 34.99,
        "sale": 0.10,
        "in_stock": True,
    },
    {
        "id": 49,
        "category_id": 9,
        "slug": "ceramic-home-figure",
        "name": "Ceramic Home Figure",
        "image": "https://images.unsplash.com/photo-1524758631624-e2822e304c36",
        "price": 18.99,
        "sale": 0.05,
        "in_stock": False,
    },
    {
        "id": 50,
        "category_id": 9,
        "slug": "mini-vase-set",
        "name": "Mini Vase Set",
        "image": "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b",
        "price": 27.99,
        "sale": 0.00,
        "in_stock": True,
    },
]
